matrix:
  include:
    # storm-cassandra-pulling
    - language: java
      jdk: oraclejdk8
      #before_script: 
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - mvn test -B
      #after_script:

    # Viewer
    - language: node_js
      node_js:
        - node
      before_script: 
        - cd ./ViewerApp
        - npm install
      script:
        - npm test
      after_script: cd ../
      
notifications:
  email: false
