version: '3.0'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    volumes:
      - ./target:/code

  supervisor1:
    image: storm
    container_name: supervisor1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  ui:
    image: storm
    container_name: storm_ui
    command: storm ui
    links:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    container_name: redis
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6379:6379